version: '3.7'

services:
  server:
    build:
      context: .       
      dockerfile: Dockerfile
      args:
        UID: $USER_ID
        GID: $GROUP_ID
    container_name: dot-server
    command: gunicorn road_safety.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/server
      - static_volume:/home/app/server/static
      - $IMAGE_ROOT:/home/app/server/data
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - INITBUILD
    entrypoint: /home/app/server/entrypoint_prod.sh    
    restart: always
    depends_on:
      - db

  db:
    image: postgis/postgis:11-3.0
    container_name: dot-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE    

  nginx:
    build: ./nginx
    container_name: dot-nginx
    restart: always
    volumes:
      - .:/home/app/server
      - static_volume:/home/app/server/static  
      - $SSL_CERT_DIR:/a  
    ports:
      - 443:443      
      - 80:80
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IPAM_CONFIG_SUBNET}
