version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: dot-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/server
    ports:
      - 8000:8000
    entrypoint: /home/app/server/entrypoint.sh  
    depends_on:
      - db
  db:
    image: postgis/postgis:12-master
    container_name: dot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
