version: '3.7'

services:
  server:
    build:
      context: .       
      dockerfile: Dockerfile
      args:
        UID: $USER_ID
        GID: $GROUP_ID
    container_name: dot-server
    command: gunicorn road_safety.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/server
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    entrypoint: /home/app/server/entrypoint.sh    
    depends_on:
      - db

  db:
    image: postgis/postgis:12-master
    container_name: dot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE    

volumes:
  postgres_data:      
