#!/bin/bash

#SBATCH --job-name=d14-939-954
#SBATCH --output=output.d14-939-954
#SBATCH --error=output_err.d14-939-954
#SBATCH -p gpu
#SBATCH -c 16
#SBATCH --mem-per-cpu=2048
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=satusky@renci.org

## Load gcc
module load gcc/11

## Load the python interpreter
source ~/.bashrc
source activate oneformer

## Execute the python script
bash oneformer_predict_loop.sh d14 939 954