# Generated by Django 3.1.1 on 2020-10-03 01:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=5)),
                ('image_base_name', models.CharField(max_length=8)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
