# Generated by Django 3.1.1 on 2020-10-16 18:57

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rs_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationSet',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pt', 'Point'), ('cont', 'Continuous')], default='pt', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RouteImage',
            fields=[
                ('route_id', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=5)),
                ('image_base_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_centainty_score', models.FloatField(default=-1)),
                ('pred_timestamp', models.DateTimeField(blank=True, null=True)),
                ('feature_present', models.BooleanField(blank=True, null=True)),
                ('annotator_timestamp', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.annotationset')),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.routeimage')),
            ],
            options={
                'unique_together': {('image', 'annotation', 'annotator')},
            },
        ),
    ]
