# Generated by Django 3.1.1 on 2020-10-20 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rs_core', '0002_annotationset_imageannotation_routeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('certainty', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='imageannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imageannotation',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='imageannotation',
            name='annotator',
        ),
        migrations.RemoveField(
            model_name='imageannotation',
            name='image',
        ),
        migrations.AddIndex(
            model_name='routeimage',
            index=models.Index(fields=['image_base_name'], name='rs_core_rou_image_b_eff58f_idx'),
        ),
        migrations.DeleteModel(
            name='ImageAnnotation',
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.annotationset'),
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.routeimage'),
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiimageannotation',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.annotationset'),
        ),
        migrations.AddField(
            model_name='aiimageannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.routeimage'),
        ),
        migrations.AddIndex(
            model_name='userimageannotation',
            index=models.Index(fields=['image', 'annotation'], name='rs_core_use_image_i_b448f4_idx'),
        ),
        migrations.AddIndex(
            model_name='aiimageannotation',
            index=models.Index(fields=['image', 'annotation'], name='rs_core_aii_image_i_d04ca4_idx'),
        ),
    ]
