# Generated by Django 3.1.1 on 2020-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0003_auto_20201020_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimageannotation',
            name='presence_views',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
