# Generated by Django 3.1.1 on 2020-12-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0004_userimageannotation_presence_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeimage',
            name='mile_post',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
