# Generated by Django 3.1.1 on 2021-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0007_routeimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimageannotation',
            name='uncertainty_measure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
