# Generated by Django 3.1.1 on 2021-01-28 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rs_core', '0008_auto_20210127_0328'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routeimage',
            name='rs_core_rou_route_i_b54be0_idx',
        ),
        migrations.AlterField(
            model_name='routeimage',
            name='route_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='aiimageannotation',
            unique_together={('image', 'annotation')},
        ),
        migrations.AlterUniqueTogether(
            name='userimageannotation',
            unique_together={('user', 'image', 'annotation')},
        ),
    ]
