# Generated by Django 3.1.1 on 2021-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0009_auto_20210128_1803'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiimageannotation',
            index=models.Index(fields=['annotation', '-uncertainty_measure', 'image'], name='rs_core_aii_annotat_f5b1cd_idx'),
        ),
    ]
