# Generated by Django 3.1.1 on 2021-02-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0010_auto_20210204_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimageannotation',
            name='uncertainty_measure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
