# Generated by Django 3.1.1 on 2021-02-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0011_auto_20210204_2053'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aiimageannotation',
            name='rs_core_aii_annotat_f5b1cd_idx',
        ),
        migrations.AddField(
            model_name='aiimageannotation',
            name='uncertainty_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='aiimageannotation',
            index=models.Index(fields=['annotation', 'uncertainty_group', '-uncertainty_measure', 'image'], name='rs_core_aii_annotat_a4271a_idx'),
        ),
    ]
