# Generated by Django 3.1.1 on 2021-02-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0012_auto_20210204_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationFlag',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userimageannotation',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='userimageannotation',
            name='presence_views',
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='front_view',
            field=models.CharField(choices=[('a', 'Absent'), ('p', 'Present'), ('i', 'Irrelevant')], default='i', max_length=10),
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='left_view',
            field=models.CharField(choices=[('a', 'Absent'), ('p', 'Present'), ('i', 'Irrelevant')], default='i', max_length=10),
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='right_view',
            field=models.CharField(choices=[('a', 'Absent'), ('p', 'Present'), ('i', 'Irrelevant')], default='i', max_length=10),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='annotations', to='rs_core.AnnotationFlag'),
        ),
        migrations.AddField(
            model_name='userimageannotation',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='user_annotations', to='rs_core.AnnotationFlag'),
        ),
    ]
