# Generated by Django 3.1.1 on 2021-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0013_auto_20210211_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimageannotation',
            name='al_round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='aiimageannotation',
            index=models.Index(fields=['uncertainty_group'], name='rs_core_aii_uncerta_217593_idx'),
        ),
    ]
