# Generated by Django 3.1.1 on 2021-02-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0013_auto_20210211_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimageannotation',
            name='presence',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='aiimageannotation',
            index=models.Index(fields=['uncertainty_group'], name='rs_core_aii_uncerta_217593_idx'),
        ),
        migrations.AddIndex(
            model_name='userimageannotation',
            index=models.Index(fields=['user', 'annotation', 'presence', 'image'], name='rs_core_use_user_id_629c3d_idx'),
        ),
    ]
