# Generated by Django 3.1.7 on 2021-04-06 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rs_core', '0014_auto_20210217_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnotationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.annotationset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
