# Generated by Django 3.1.8 on 2021-04-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0015_userannotationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannotationsummary',
            name='presence',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userannotationsummary',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
