# Generated by Django 3.1.8 on 2021-05-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0017_routeimage_aspect_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldoutTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(db_index=True)),
                ('presence', models.BooleanField(db_index=True, default=False)),
                ('in_balance_set', models.BooleanField(db_index=True, default=True)),
                ('certainty', models.FloatField()),
                ('left_certainty', models.FloatField()),
                ('front_certainty', models.FloatField()),
                ('right_certainty', models.FloatField()),
                ('category', models.CharField(choices=[('tp', 'TruePositive'), ('tn', 'TrueNegative'), ('fp', 'FalsePositive'), ('fn', 'FalseNegative')], max_length=10)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.annotationset')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rs_core.routeimage')),
            ],
        ),
    ]
