# Generated by Django 3.1.8 on 2021-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0018_holdouttestinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimageannotation',
            name='presence',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
