# Generated by Django 3.1.8 on 2021-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_core', '0019_auto_20210621_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeimage',
            name='route_index',
            field=models.IntegerField(default=-1),
        ),
    ]
